feat: increment 13
EvgeniyBudaev/shortener pull request #13
Opened 2023-10-07 18:15 UTC by EvgeniyBudaev

2023-10-15 08:25 UTC, kilchik requested changes

2023-10-15 08:25 UTC, kilchik commented on internal/store/fs/store.go
> +	return id, s.sw.AppendToFile(&models.URLRecord{UUID: strconv.Itoa(s.UrlsCount), OriginalURL: url, ShortURL: id})
UrlsCount не защищена мьютексом, а это значит, что если 10 клиентов в разных горутинах выполняют функцию Put, то они поменяют ее значение до 10 раз прежде, чем первый клиент вызовет AppendToFile, т е значение UrlsCount окажется некорректным

2023-10-15 08:25 UTC, kilchik commented on internal/store/fs/store.go
> +		} else if err != nil {
else не нужен

2023-10-15 08:25 UTC, kilchik commented on internal/store/postgres/store.go
> +	row := db.conn.QueryRow(context.Background(), "SELECT original_url FROM shortener WHERE slug = $1", id)
context должен пробрасываться из хэндлера. Собственно все запросы к БД должны быть с контекстом из клиентского запроса. 
В противном случае велика вероятность, что при временном подвисании запросов к БД клиентские соединения будут завершаться по таймауту, а соединения с БД будут продолжать висеть, пока новые клиентские соединения не приведут к достижению лимита по установленным соединениям, в результате чего сервис драматически деградирует.
Более простой пример: пришел запрос с таймаутом -> QueryRow выполнялась дольше таймаута -> клиент уже отвалился, а мы что-то пишем или забираем из БД

2023-10-17 06:59 UTC, EvgeniyBudaev commented on internal/store/fs/store.go
> +	return id, s.sw.AppendToFile(&models.URLRecord{UUID: strconv.Itoa(s.UrlsCount), OriginalURL: url, ShortURL: id})
Многопоточность будет в следующем спринте, но я попробовал сделать

2023-10-17 06:59 UTC, EvgeniyBudaev commented on internal/store/fs/store.go
> +		} else if err != nil {
Поправил

2023-10-17 06:59 UTC, EvgeniyBudaev commented on internal/store/postgres/store.go
> +	row := db.conn.QueryRow(context.Background(), "SELECT original_url FROM shortener WHERE slug = $1", id)
Поправил

2023-10-19 15:34 UTC, kilchik approved these changes

2023-10-20 04:36 UTC, merged